version: "3.8"

services:
  web:
    build: .
    image: tsdip-web
    container_name: tsdip-web
    # env_file: .env
    ports:
      - "3000:3000"
    networks:
      - tsdip
    # volumes:
    #   - ./:/app

networks:
  tsdip:
    name: tsdip-network
    external: true
