apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 80
    type: http
    requestPath: /
  logging:
    enable: true
    sampleRate: 0.5
  # iap:
  #   enabled: true
  #   oauthclientCredentials:
  #     secretName: my-secret
