apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backendConfig.yaml
  - deployment.yaml
  - ingress.yaml
  - managedcertificate.yaml
  - service.yaml

configMapGenerator:
  - name: cm-env
    literals:
      - API_URL=http://tsdip-api-svc
