name: Docker Image CI

on:
  push:
    branches:
      - 'feature/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: hallee/eslint-action@1.0.3
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          source-root: optional-sub-dir
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRE_TAG: ${GITHUB_REF#refs/tags/}
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/taiwolskit/tsdip-web/tsdip-web:${GITHUB_REF#refs/heads/feature/}-$GITHUB_SHA
      - name: publish docker image to Github package registry
        run: docker push docker.pkg.github.com/taiwolskit/tsdip-web/tsdip-web:${GITHUB_REF#refs/heads/feature/}-$GITHUB_SHA
