apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: tsdip-web-

commonLabels:
  project: tsdip
  app: web

images:
  - name: tsdip-web
    newTag: demo
    newName: asia-east1-docker.pkg.dev/tsdip-dev/tsdip-web/tsdip-web
